### ISSUE TITLE
How to unpack asar archive?

### ISSUE THREAD

**Issue by MidKnightXI** [Absolucy/asar-rs#1]
# Context

I'm looking to unpack a .asar archive to rewrite some files in it.

I already did this in JS with the [asar](https://www.npmjs.com/package/@electron/asar) npm package from electron and I'm trying to rewrite this code in Rust due to "performance issues" and that I'm not satisfied with my own code.

# JS Code with asar lib

Just to give you an exemple of what I'm trying to reproduce

```js
import { extractAll, createPackageWithOptions } from "asar";
import { readdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { sync } from "rimraf";
import { dirname, normalize } from "path";
import { spawn } from "child_process";

function replaceAdFileContent(path) {
  let content = readFileSync(path).toString();

  content = content.replaceAll(
    "https://dtapp-player.op.gg/adsense.txt",
    "https://gist.githubusercontent.com/MidKnightXI/7ecf3cdd0a5804466cb790855e2524ae/raw/9b88cf64f3bb955edfff27bdfba72f5181d8748b/remover.txt"
  );
  content = content.replace(
    /exports\.countryHasAds=\w;/gm,
    "exports.countryHasAds=[];"
  );
  content = content.replace(
    /exports\.countryHasAdsAdsense=\w;/gm,
    "exports.countryHasAdsAdsense=[];"
  );
  content = content.replace(
    /exports\.adsenseAds=\w;/gm,
    "exports.adsenseAds=[];"
  );
  content = content.replace(
    /exports\.playwireAds=\w;/gm,
    "exports.playwireAds=[];"
  );
  content = content.replace(
    /exports\.nitropayAds=\w;/gm,
    "exports.nitropayAds=[];"
  );
  writeFileSync(path, content);
}

async function rebuildAddDir(asarFilePath) {
  console.log("Unpacking OPGG asar file");
  extractAll(asarFilePath, "op-gg-unpacked");

  const assetDir = normalize("op-gg-unpacked/assets/react");
  const assetFiles = readdirSync(assetDir);

  for (let fileName of assetFiles) {
    if (fileName.endsWith(".js")) {
      console.log(`Patching: ${fileName}`);
      replaceAdFileContent(normalize(`${assetDir}/${fileName}`));
    }
  }

  console.log(`Rebuilding ${asarFilePath} without ads urls`);
  await createPackageWithOptions("op-gg-unpacked", asarFilePath, {
    unpackDir: "{node_modules/node-ovhook,node_modules/rust-process}",
  });

  console.log(`Deleted temporary directory`);
  sync("op-gg-unpacked");
}
```

I tried to open a .asar with your crate (with the exemple provided and the path to my archive but it ends up not listing its content

**Comment by MidKnightXI** [comment]
Btw I used the function you provided like that

```rs
fn rebuild_ad_dir(path: &str) -> Result<()>
{
    let asar_file = std::fs::read(path)?;
    let asar = AsarReader::new(&asar_file)?;

    println!("There are {} files in archive.asar", asar.files().len());
    for content in asar.files().keys() {
        println!("{}", content.display());
    }
    Ok(())
}

pub fn remove_ads() -> bool
{
    let asar: String = format_asar_path();
    let asar_path = std::path::Path::new(&asar);

    if asar_path.exists()
    {
        kill_opgg();
        // unpack_asar(asar_path.to_str().unwrap());
        let test = rebuild_ad_dir(asar_path.to_str().unwrap());
        match test {
            Ok(v) => println!("working with version: {v:?}"),
            Err(e) => println!("error parsing header: {e:?}"),
        }
        return true;
    }
    return false;
}
```

**Comment by Absolucy** [comment]
Sorry, didn't notice my GitHub notifications until now!

> Btw I used the function you provided like that

What does this program output when running `rebuild_ad_dir`?

**Comment by MidKnightXI** [comment]
Sorry I didn't work on my stuff lastly but I just checked and it appears that I'm getting this error:
```
error parsing header: Json(Error("data did not match any variant of untagged enum Header", line: 0, column: 0))
```

**Comment by MidKnightXI** [comment]
the `path`value is given with this function.

```rs
fn format_asar_path() -> String
{
    let path: String;

    if std::env::consts::OS == "macos"
    {
        path = "/Applications/OP.GG.app/Contents/Resources/app.asar".to_string();
    }
    else if std::env::consts::OS == "windows"
    {
        match std::env::var("APP_DATA") {
            Ok(k) => path = format!("{}/Local/Programs/OP.GG/resources/app.asar", k),
            Err(e) => panic!("$APP_DATA is not set ({})", e)
        }
    }
    else
    {
        panic!("Your OS isn't compatible with this script");
    }
    return path;
}
```

**Comment by Absolucy** [comment]
What does app.asar look like? Can you upload the asar somewhere (use [catbox.moe](https://catbox.moe) if you don't already use another file uploading site) so I can take a look at it?

**Comment by MidKnightXI** [comment]
here's a link to the [archive](https://temp.sh/ERuzP/app.asar.zip)

**Comment by MidKnightXI** [comment]
@Absolucy Can I have some updates on this please?

**Comment by MidKnightXI** [comment]
[Here is a new link to the archive](https://files.catbox.moe/7fw4c6.zip)

**Comment by Furry** [comment]
I'm having the same issue, with an identical error code to the one posted by @MidKnightXI when attempting to read an electron app.

**Comment by Absolucy** [comment]
Sorry for taking an eternity and a half, I've figured out the issue.

![image](https://user-images.githubusercontent.com/65794972/210425194-8466716e-360f-4615-bd96-6fde6f21f70c.png)

Some objects seem to have an `unpacked` value. I'm not entirely sure what this does?

**Comment by Absolucy** [comment]
Should be fixed with https://github.com/Absolucy/asar-rs/commit/97db6737d4d855a087c1882d234c6569014c70f5

**Comment by MidKnightXI** [comment]
So cool, I began to write my own unpacker because of that. But I'm struggling after reading the header, I don't know what to do to be honest !

**Comment by MidKnightXI** [comment]
Is it possible for you to make a release on crates.io when it's possible?

**Comment by MidKnightXI** [comment]
> Should be fixed with [97db673](https://github.com/Absolucy/asar-rs/commit/97db6737d4d855a087c1882d234c6569014c70f5)

Would it be possible for you to create a new release on [crates.io](https://crates.io/crates/asar) so everyone can use it properly please?

**Comment by Absolucy** [comment]
Sure.

**Comment by Absolucy** [comment]
0.2.0 published on crates.io.
